### PR TITLE
Control the patient delete button with a global entry, defaults to off

### PR DESCRIPTION
**Pull request by teryhill**
Control the patient delete button with a global entry, defaults to off

### CODE REVIEW

**Comment by aethelwulffe** [comment]
Looks totally clean to me, but what about the database default?

**Comment by tmccormi** [comment]
not sure what you mean @aethelwulffe about the database default?

**Comment by aethelwulffe** [comment]
Meaning set the field with a default =1 value...in the table structure 
when it created...

CREATE TABLE `list_o_crap`

(`blah` varchar(42) NOT NULL,

`active` bool DEFAULT 1);

**Comment by aethelwulffe** [comment]
I redact my stupid comment.  All the same, as an upgrade, the user would have had the ability to delete, and now they will not...unless they go looking into globals admin.  Just something to keep in mind.  In reality, it just highlights the need for lots more "setting up your practice" documentation. *sigh*

**Pull request merged**
