### PR TITLE
Move menu JSON to sites dir as a nicely formatted file 

### PR DESCRIPTION
**Pull request by tmccormi**
and add template variable replacement.

### CODE REVIEW

**Comment by tmccormi** [comment]
This is part of #17 menu usability

**Comment by tmccormi** [comment]
@aethelwulffe @teryhill any reason not to merge this for the release?

**Comment by teryhill** [comment]
It looked good to me from a ode stand point. Did not test it.

**Comment by aethelwulffe** [comment]
If this has been run by you @tmccormi , then it either works or it doesn't.  I would rather test again at RC1.  I see no syntax errors, though I didn't look up that mysterious sounding $usermenufile

**Comment by tmccormi** [comment]
Done and merged.

**Comment by aethelwulffe** [comment]
I was just getting used to the squashed-up stuff.  Kinda liked it!  Wasn't prudent though.

**Pull request closed without merging**
