### PR TITLE
Trying to help the readability of the file

### PR DESCRIPTION
**Pull request by teryhill**
Trying to help the readability of the file this would be work on #3 of
milestone#1

### CODE REVIEW

**Comment by tmccormi** [comment]
sure, but why are we just loading the sql into the database and using it in table format instead of JSON?

**Comment by tmccormi** [comment]
I'll merge this in the meantiime, it's a good tweak

**Comment by teryhill** [comment]
trying to help move the milestone. It just said documentation.

**Comment by aethelwulffe** [comment]
DOC >U< MENTATION.

**Pull request merged**
