### PR TITLE
remove ICD9 from external data upload

### PR DESCRIPTION
**Pull request by teryhill**
remove ICD9 from external data upload #110

### CODE REVIEW

**Comment by aethelwulffe** [comment]
Took some looking due to all the elseif structure, but looks good.  I will test after master ->dev merge.

**Comment by teryhill** [comment]
Just leave it . It needs to be left till we remove ALL the dependencies .

**Comment by tmccormi** [comment]
This was merged into development, not master.  So I will need to cherry pick...

**Comment by aethelwulffe** [comment]
Hopefully, we remember to snuff and DSMIV stuff as a code type as well...

**Comment by aethelwulffe** [comment]
...and no problem guys...just keep going.  I will continue to rebuild the windows package over and over again! 😈  (Gets a little better each time anyway).

**Pull request merged**
