### PR TITLE
Fix issues and inconsistency in database.sql - issue #99

### PR DESCRIPTION
**Pull request by tmccormi**
A lot of this is deleted meaningless comment line separators and

- adding DROP IF EXISTS to all CREATES
- adding quotes on all table and field identifiers
- fixing the lists_touch table defaults

### CODE REVIEW

**Comment by tmccormi** [comment]
I think I should change all ENGINE= to InnoDB (that's a recent update in OpenEMR)

**Comment by teryhill** [comment]
There were some issues with the autoincrement and incrementing of the tables under InnoDB Be wery wery karful

**Comment by tmccormi** [comment]
I made the INNODB changes.   There are some notes about auto-increment changes in the DB ...  not many and none seemed relevant to me.   Specifics, perhaps?   I vaguely remember the discussion on SF

**Comment by teryhill** [comment]
interface/billing/edit_payment.php for one

 				 {
 -				  sqlStatement("insert into ar_activity set "    .
 +					 sqlBeginTrans();
 +					 $sequence_no = sqlQuery( "SELECT IFNULL(MAX(sequence_no),0) + 1 AS increment FROM ar_activity WHERE pid = ? AND encounter = ?", array(trim(formData("HiddenPId$CountRow"   )), trim(formData("HiddenEncounter$CountRow"   ))));
 +					 sqlStatement("insert into ar_activity set "    .

**Comment by aethelwulffe** [comment]
I guess I need to take a live database, dump the inserts, bring in the sites directory, then try to process era's against this to be able to test the innoDB changed.  That is where the biggest issues were when this was last tried.  @teryhill I don't see that MAX value query.  Is that something out of the OpenEMR codebase?

**Comment by tmccormi** [comment]
Yes those MAX value changes are part of recent OpenEMR.  No reason we can't make just the effected files MyISAM instead of INNODB, mixed ENGINE types are supported

**Comment by aethelwulffe** [comment]
Selecting MAX value for autoincrement is not a great idea.
```
UPDATE table_1 
SET marked_by_connection_id = CONNECTION_ID(), 
    marked_time = NOW()
WHERE worktime < UNIX_TIMESTAMP() AND marked_by_connection_id IS NULL;
```
The issue with the above is that if the session dies, you gotta have a cron job to clean up.
Using another table to store a value, then only allowing new inserts from the "temporary" table, provided that they are also marked by time, and if used, and are afterwards deleted after the row is pushed to the final table is a pretty dependable process, but you have to make sure that the whole application talks to the ar_session table the same way.
Soooo...I guess I have said nothing.  Locked tables are a pain. all that.  What is the downside to having mixed engine and engine defaults in the table creation?  Also, are we ensuring that default collation is UTF8 general?

**Comment by tmccormi** [comment]
I am no SQL expert .... here's what I think.
1) Agree that using MAX sucks, autoincrement is better, fixing the DB to be INNODB compliant by NOT using auto-increment field in compound primary keys (if I understand the problem)  @yehster does...
2) Transactions ...  we could allow MySQL to have transaction commit and roll back.
3) Mixed engines seem to be fine, I've got lots of sites using it that way.

**Comment by aethelwulffe** [comment]
I hate having an incongruous foundation, but yeah, I think we need to use both engines...in a controlled way.

**Comment by tmccormi** [comment]
It risk avoidance ...  OK for now so we can get to RELEASE which is nearly a month late...

**Comment by tmccormi** [comment]
Any feedback here? I would like to get this merged

**Comment by teryhill** [comment]
Pull request 130 is where the changes for the max were introduced, I would think leaving the tables that they used Max on as MyISAM would be prudent

**Comment by tmccormi** [comment]
This is what I find ...  Look right?

1. ar_activity
2. ar_session
3. claims
4. procedure_order_code
5. procedure_answers

**Comment by teryhill** [comment]
It should be any tables that uses the compound key and I think there were just a few files. So that looks right, I would question if billing should be included but I am not sure what the key is for it . I am working on statement changes.

**Comment by tmccormi** [comment]
billing did not show up with a MAX() function anywhere in that pull 130 so I have pushed these for now.

**Comment by aethelwulffe** [comment]
I will test tonight when I get back.

**Comment by tmccormi** [comment]
Did you delete my branch instead of merging it? @aethelwulffe

**Comment by aethelwulffe** [comment]
Didn't intend to do either one.  Please re-publish!  Mia Coupa Mia Coupa!

**Comment by aethelwulffe** [comment]
Up arrow autocomplete is bad.  Switching back to github windows application.... :octocat:

**Comment by aethelwulffe** [comment]
Merged, and testing again (php5.7).

**Comment by tmccormi** [comment]
Thanks!

**Pull request merged**
