### PR TITLE
Copyright kevins code

### PR DESCRIPTION
**Pull request by teryhill**
These are the files with out copyrights in the headers

### CODE REVIEW

**Comment by teryhill** [comment]
@tmccormi  Here are Kevin's files wit the short copyright

**Comment by tmccormi** [comment]
@kevin is this OK with you?

**Comment by tmccormi** [comment]
No response from Kevin, but he told me a while back it was OK with what ever we decided on for License.  So... merging.

**Comment by teryhill** [comment]
@tmccormi can you check to make sure this is still in the code . I do not see it

**Comment by tmccormi** [comment]
Merged into Master on Sept 25th
https://github.com/LibreEHR/LibrEHR/commit/8bec255e4f3aa831fd2533d46cb51f10ad3d9a9c

```
/opt/gitrepos/LibreEHR (master)$ git blame interface/main/tabs/css/menu.css
8bec255e (Terry Hill     2016-09-25 15:48:11 -0400  1) /* 
8bec255e (Terry Hill     2016-09-25 15:48:11 -0400  2)  * Copyright (C) 2016 Kevin Yeh <kevin.y@integralemr.com>.
8bec255e (Terry Hill     2016-09-25 15:48:11 -0400  3)  * Licensed to the public under the MPL-HD license at www.librehealth.io.
8bec255e (Terry Hill     2016-09-25 15:48:11 -0400  4)  */
8bec255e (Terry Hill     2016-09-25 15:48:11 -0400  5) 
```

**Comment by teryhill** [comment]
Ok I will look again 
Thanks

**Pull request merged**
