### PR TITLE
dated reminders #144  user selection box ORDER, WHERE, and size change

### PR DESCRIPTION
**Pull request by aethelwulffe**
Alphabetize the user dropdown list, ensure that the list contains only
real local users by checking some additional fields, make the select
show 8 instead of the default 5, and set the list of reminders to 15
instead of just 5.  One heavy user has theirs set to 50, so this is a
minimal compromise.

### CODE REVIEW

**Comment by tmccormi** [comment]
Is cal_ui the right flag to check for "real users" ?  Or am I mis reading that?

**Comment by aethelwulffe** [comment]
Actually, we don't have to include that, but at one point PHImail and other users were showing up.  There were so many issues with fakeroos showing up that I decided (a few years ago) to keep adding fields until weird shit disappeared.  That was actually not the last one.  The last one was AND u.id >1.  You personally busted me on that, stating that some folks used the admin user, or changed the name, or (now-a-days) bothered to set the default user during install.  That one I took out of this edition.
  I just tested all this against a non-tabs install (you know who) because there are about a thousand users, and they were not alpha-listed, had junk user accounts, and a tiny window to hunt and peck in.  More to the point, the OTHER fork just junked my ancient stale pull request with this in it, bringing that to light.

**Comment by tmccormi** [comment]
Just want to make sure that the user's don't have to be "calendar" enabled to be on the messages pick list,

**Comment by aethelwulffe** [comment]
No, that is the UI, not the listing on the schedule.

**Comment by aethelwulffe** [comment]
Testing version Alpha 1 of the installer right now.  Need to change the default directory to "xampp" and not "LibreEHR", I want better license, pre-install and post-install instruction pages (in RTF), as well as the actual release version...and to not accidentally have a second test branch install in the package...But IT WORKDED!

**Comment by aethelwulffe** [comment]
Oh yeah....I need to make a favicon for both the Installer icon as well as the application favicon for the EMR.  Using a transparent sunburst right now.

**Comment by aethelwulffe** [comment]
Suggestions?

[Setup]

AppId={{3C5096D4-63FA-40BD-A8B7-6C8327698888}
AppName=LibreEHR
AppVersion=1.0
;AppVerName=LibreEHR 1.0
AppPublisher=LibreEHR
AppPublisherURL=http://LibreEHR.org/
AppSupportURL=http://LibreEHR.org/
AppUpdatesURL=http://LibreEHR.org/
DefaultDirName=c:/LibreEHR
DisableProgramGroupPage=yes
LicenseFile=C:\xampp\htdocs\LibreEHR\license.txt
InfoAfterFile=C:\xampp\htdocs\LibreEHR\acknowledge_license_cert.html
OutputBaseFilename=setup
SetupIconFile=C:\Users\Art\Desktop\spr_sun_35e_icon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "catalan"; MessagesFile: "compiler:Languages\Catalan.isl"
Name: "corsican"; MessagesFile: "compiler:Languages\Corsican.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "danish"; MessagesFile: "compiler:Languages\Danish.isl"
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "finnish"; MessagesFile: "compiler:Languages\Finnish.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "greek"; MessagesFile: "compiler:Languages\Greek.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "norwegian"; MessagesFile: "compiler:Languages\Norwegian.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "scottishgaelic"; MessagesFile: "compiler:Languages\ScottishGaelic.isl"
Name: "serbiancyrillic"; MessagesFile: "compiler:Languages\SerbianCyrillic.isl"
Name: "serbianlatin"; MessagesFile: "compiler:Languages\SerbianLatin.isl"
Name: "slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\xampp\xampp-control.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs


[Icons]
Name: "{commonprograms}\LibreEHR"; Filename: "{app}\xampp-control.exe"
Name: "{commondesktop}\LibreEHR"; Filename: "{app}\xampp-control.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\xampp-control.exe"; Description: "{cm:LaunchProgram,LibreEHR}"; Flags: nowait postinstall skipifsilent

**Pull request merged**
