### PR TITLE
Drop PHPMyAdmin, add configurable SQL Admin, fix libreehr.org links

### PR DESCRIPTION
**Pull request by tmccormi**
Much better commit for #5

### CODE REVIEW

**Comment by tmccormi** [comment]
Has anyone had a change to look this over?

**Comment by aethelwulffe** [comment]
Everything is working ...or not working as it may be....just fine.  Did we already remove the PMA bookmarks from database.sql?

**Comment by tmccormi** [comment]
Don't know about PMA books marks but I'll take a look real quick

**Comment by tmccormi** [comment]
no, but I'll do that now.

**Pull request closed without merging**
