### PR TITLE
cure unclosable and stomp menu

### PR DESCRIPTION
**Pull request by aethelwulffe**
Needed unique names for menu items, as well as set the closable
attribute to true.

### CODE REVIEW

**Comment by aethelwulffe** [comment]
#156 #20  and others.

**Comment by tmccormi** [comment]
THis looks OK to me.  Is it good to merge?  There are tons of emails I have not caught up on yet.

**Comment by teryhill** [comment]
OpenEMR has already grabbed it

**Comment by aethelwulffe** [comment]
The openEMR version has some issues it appears.  I trashed that test 
install when doing that layout dealio, but I will pull it over and give 
it another run to make sure we don't have the same problems.  I think I 
see what their issue is...  I am sure it is a bit more useful than the 
original though.

**Comment by aethelwulffe** [comment]
Just re-tested with fresh install, and ran a few scenarios against it suggested by Terry..  Looks good.
Relevant php notices:
[Fri Sep 16 14:49:11.261190 2016] [:error] [pid 832:tid 1792] [client ::1:55770] PHP Notice:  Undefined index: plugins_started in C:\\xampp\\htdocs\\LibreEHR\\library\\pluginsystem\\PluginSystem.php on line 192, referer: http://localhost/LibreEHR/interface/patient_tracker/patient_tracker.php?skip_timeout_reset=1
[Fri Sep 16 14:49:11.261190 2016] [:error] [pid 832:tid 1792] [client ::1:55770] PHP Notice:  Undefined variable: ret in C:\\xampp\\htdocs\\LibreEHR\\library\\pluginsystem\\PluginSystem.php on line 203, referer: http://localhost/LibreEHR/interface/patient_tracker/patient_tracker.php?skip_timeout_reset=1
[Fri Sep 16 14:49:11.286806 2016] [:error] [pid 832:tid 1792] [client ::1:55770] PHP Notice:  Use of undefined constant authUserID - assumed 'authUserID' in C:\\xampp\\htdocs\\LibreEHR\\library\\patient_tracker.inc.php on line 151, referer: http://localhost/LibreEHR/interface/patient_tracker/patient_tracker.php?skip_timeout_reset=1
[Fri Sep 16 14:49:11.304619 2016] [:error] [pid 832:tid 1792] [client ::1:55770] PHP Notice:  Undefined index: pc_time in C:\\xampp\\htdocs\\LibreEHR\\interface\\patient_tracker\\patient_tracker.php on line 374, referer: http://localhost/LibreEHR/interface/patient_tracker/patient_tracker.php?skip_timeout_reset=1

**Pull request merged**
