### PR TITLE
Liberation

### PR DESCRIPTION
**Pull request by aethelwulffe**
After manually adding the globals fix, this branch installed, ran, and tested very well.  There is some odd stuff in documentation, like the "History" piece that describes the history of OpenEMR up to "current 2.0", but I think that can be snuffed.
  This may require a rebase, but if it is possible, I would rather take care of conflicts on the other branches instead of this one.
  to-be-done:  Update web links.

### CODE REVIEW

**Comment by tmccormi** [comment]
Not sure what to do with this until the conflicts are resolved.   too many file changes to look at them all, but it looks like a refactor by 'sed' so, probably OK.

**Comment by aethelwulffe** [comment]
Conflict resolution taken care of.

**Comment by aethelwulffe** [comment]
D@MMIT.  I just resolved the conflicts on this huge mess, and now it's stale again.

**Comment by aethelwulffe** [comment]
Looking messy, but it took hours of verifying the changes and testing them.  Just one conflict, and that was in globals.inc.php

**Comment by tmccormi** [comment]
First merge using my cellphone!

**Pull request merged**
