### PR TITLE
adjustment reason update ref #10 

### PR DESCRIPTION
**Pull request by aethelwulffe**
Provides a full list of all valid/current ERA adjustment codes.

### CODE REVIEW

**Comment by teryhill** [comment]
Is there one for interest?

**Comment by aethelwulffe** [comment]
Code 85

**Comment by tmccormi** [comment]
I'll take it, but why is this an array and not a list_options table?  There is an Adjustment Reason list option.

adjustment-reasons-list

**Comment by aethelwulffe** [comment]
To ensure it is not user configurable would be one reason.  If there was a cleaner choice of vertical table, I could go for that, but I can't see tossing a static data set into list_options as being a real help.  I would rather see it in a codes table where it belongs.  Right now we just need the keeper pieces of the billing code simple as they can be.

On August 31, 2016, at 03:01, Tony McCormick <notifications@github.com> wrote:

I'll take it, but why is this an array and not a list_options table? There is an Adjustment Reason list option.

￼

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LibreEHR/LibreEHR","title":"LibreEHR/LibreEHR","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/LibreEHR/LibreEHR">https://github.com/LibreEHR/LibreEHR</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tmccormi in #138: I'll take it, but why is this an array and not a list_options table? There is an Adjustment Reason list option.\r\n\r\nadjustment-reasons-list\r\n"}],"action":{"name":"View Pull Request","url":"<a href="https://github.com/LibreEHR/LibreEHR/pull/138#issuecomment-243676274">https://github.com/LibreEHR/LibreEHR/pull/138#issuecomment-243676274</a>"}}}

**Pull request merged**
