### PR TITLE
end_of_file_fix #103 

### PR DESCRIPTION
**Pull request by aethelwulffe**
Function did not close, most of code was wrapped in one function.  No
idea how it was supposed to work before.

### CODE REVIEW

**Comment by teryhill** [comment]
fix #86 fixed this

**Comment by aethelwulffe** [comment]
Sorry, I guess I need to rebase the freeb branch, as that is what I had to fix to get to the point where I could test it, but I did this against a fresh master, and it looks like my changes are a little more extensive.  I will leave the pull request in there for review.  If these are deemed unnecessary, then drop the pull request and branch.

**Comment by tmccormi** [comment]
Seems a lot more than and end of file fix.   What's the purpose of these changes?

**Comment by aethelwulffe** [comment]
Flushing the toilet before company comes over.  I know it's just pee and all, but...

The end of file issue was, frankly, due to playing loose and fast with braces...like not using them.  Also, there are empty methods, repetitively assigned variables, unused hooks and other bits that should be commented on or removed.
  If a basic IDE screams about something just not being right...you know...just bring it up to standard.  I am not saying we have to limit functions to 20 lines or something stupid like that...  It's just that I forgot a closing bracket on the the 800 line function gen_x12_837, and maybe I am trying to compensate.

**Comment by tmccormi** [comment]
All, good but try to use your words and actually describe the fix(es) in one sentence that is meaningful when you look at a commit history gitlog next year ... :-)

**Comment by tmccormi** [comment]
Hello?  should I merge this or not?

**Comment by aethelwulffe** [comment]
Terry has a down vote.

**Comment by tmccormi** [comment]
not merging this one....

**Pull request closed without merging**
